### ISSUE TITLE
iOS devices stops receiving push notifications

### ISSUE THREAD

**Issue by KrishnaPatell** [QuickBlox/quickblox-ios-sdk#1061]
Hello Team,

I'm facing this issue from 29 June 2018 in my two projects.
I'm using 2.16 SDK version.
I've tried to send notification from dashboard, from app and from our server(our own control panel) but not working. It shows that notification successfully send but iOS receiver cannot receive notification anymore.
On dashboard its always shows me "Delivered: 0, failed: 0"
On other hand android devices gets notification perfectly.

**Log of notification found from dashboard ->  push notification -> queue ->** 

{"notification":{"id":15380965,"badge":null,"device_token":"4ff7691f8082fbfb436ce13a2778082f7d95e982bc9447f4d5acfa400930be76","sound":null,"alert":{"title":"Notification from Taxisti","body":"55646456"},"data":{"type":"admin_notification","body":"55646456","title":"Notification from Taxisti","headers":{"apns-topic":"com.yahya.Taxisti"}},"expiry":86400,"delivered":false,"delivered_at":null,"failed":false,"failed_at":null,"fail_after":"2018-06-30T05:08:40+00:00","retries":10,"error_code":null,"error_description":null,"deliver_after":"2018-06-30T04:09:31+00:00","alert_is_json":null,"app_id":22873,"collapse_key":null,"delay_while_idle":null,"registration_ids":null,"uri":null,"priority":null,"url_args":null,"category":null,"content_available":false,"mutable_content":false,"notification":null,"type":"Rpush::Client::Redis::Apns::Notification","event_id":24691718,"event_date":"2018-06-30T04:08:40+00:00"},"log":[{"device_token":"4ff7691f8082fbfb436ce13a2778082f7d95e982bc9447f4d5acfa400930be76","delivered_at":null,"failed_at":null,"error_code":null,"error_description":null}]}

**Log from certificates** 

Certificate errors:

APNS feedback service (development), last 14 days:

Please Guys do something on this major issue.

**Comment by kmittal98** [comment]
Do you have any build on the App Store? I mean on production environment? Check with that

**Comment by KrishnaPatell** [comment]
@kmittal98 
No I don't have any build uploaded on Appstore, my app is in development mode and suddenly it stops receiving notification. 😞

**Comment by kmittal98** [comment]
Any updates?

**Comment by orlovev88** [comment]
we have same problem with our app. dev environment didn't work, but build from testflight works without any errors.

**Comment by KrishnaPatell** [comment]
Are Quickblox team working on this major issue? They even didn't reply for the ticket that I've generated.

**Comment by kmittal98** [comment]
@orlovev88  is it start with 29 June in your case too?

**Comment by orlovev88** [comment]
@kmittal98 yes, from 29 June too.

**Comment by paviesf** [comment]
@kmittal98 yes, My case too, My Client is so angry with me. monday was the deadline for submission

**Comment by romansorochak** [comment]
I have same issue too.
do not receive push notifications when send it from the latest ios SDK either when send from quickblox admin panel
I cannot even submit a ticket cuz it asks some strange customer id (account id from quickblox profile settings does not accept)

Quickblox support please help !

**Comment by vineeshtp** [comment]
I have same problem. I already send mail to quickblox but, no response from th
em.

**Comment by RubenBenBen** [comment]
@KrishnaPatell @kmittal98 any updates guys?

**Comment by KrishnaPatell** [comment]
hi @RubenBenBen,
QB says that issue is resolved but it is still pending. we cannot receive notification in development mode but can receive Push in production mode.

**Comment by paviesf** [comment]
There is still issue cannot receive notification in development mode. But it is worked fine in production mode.  Use production certificate to create ad-hoc build and test it.

**Comment by Dhananjay22** [comment]
@VitaliyGuru
@andr45
@iSevenDays
@Berk0ld

is there any update on this issue? I am still facing the issue.
is Quickblox team has started fixing this issue?

**Comment by KrishnaPatell** [comment]
Hi @kmittal98 @orlovev88 @RubenBenBen 
Can you guys please check with your production build for push notification?
I think its not working too.
Please check push notification in production environment.

**Comment by orlovev88** [comment]
@KrishnaPatell 

notifications for last week worked. but from this week we implemented sending notification from our server. we didn't receive any proper help from qb team. just general information how to upload and create notification. when we provided logs from our admin panel with information that notification not delivered - they said that they haven't detected any issues on Quickblox or Apple Channel side yet.

**Comment by KrishnaPatell** [comment]
@orlovev88 
Have you tried with Production push certificates?
In my case, its working fine till yesterday but today iOS devices just stopped receiving notification.
I don't know what is the issue with Quickblox.

**Comment by orlovev88** [comment]
@KrishnaPatell yes, we used Production certificate with qb until monday. i can check push with previous builds and provide for you information tomorrow.

**Comment by KrishnaPatell** [comment]
@orlovev88 
Okay.. Please tell me tomorrow for this issue.
I also tried to send notification from QB dashboard (Live environment) but not receiving in iOS devices.
Please check this too.

**Comment by orlovev88** [comment]
@KrishnaPatell i checked it - notification didn't work from device or admin panel.

**Comment by KrishnaPatell** [comment]
@orlovev88 
Thanxx For update.
Can Anyone have solution for this problem??

**Comment by RubenBenBen** [comment]
https://quickblox.com/blog/push-notifications-issues-resolved-on-shared-instance-enterprise-customers-please-click-here-3/

**Comment by KrishnaPatell** [comment]
Thanxx @RubenBenBen for the update
