### ISSUE TITLE
Crash when sending userinfo with video call

### ISSUE THREAD

**Issue by pwsharma** [QuickBlox/quickblox-ios-sdk#1105]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

https://github.com/QuickBlox/quickblox-ios-sdk/issues/712

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 12.0.1                                    |                                          
Quickblox iOS SDK version      |  2.7.6                                  |
QuickbloxWebRTC SDK version    | 2.7                                  |                               
Xcode Version                  | Xcode 10.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?   |

**Did this work before?**
No, it never worked for video call. Works fine for audio calls

**Expected behavior**
When we send **UserInfo** with a call at receivers end it should be received with new session object.

**Actual behavior**
When we send **UserInfo** with a call at receivers end it application is crashing with the error message. It only happens when we send user info with video call. In case of audio call it works fine.

-[__NSCFConstantString count]: unrecognized selector sent to instance 0x10626b120

**Logs**
<summary>Crash log in debugger </summary>
// Your logs here
2018-11-14 15:12:09:153 Howdoo[847:9907] SEND: <?xml version='1.0'?>
2018-11-14 15:12:09:154 Howdoo[847:9907] SEND: <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' to='chat.quickblox.com' from='67317950-74447@chat.quickblox.com'>
2018-11-14 15:12:09.154743+0530 Howdoo[847:215070] [] nw_connection_copy_connected_path [C9] Client called nw_connection_copy_connected_path on unconnected nw_connection
2018-11-14 15:12:09.154773+0530 Howdoo[847:215070] [] tcp_connection_is_cellular No connected path
2018-11-14 15:12:10:678 Howdoo[847:7803] RECV: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" from="chat.quickblox.com" id="326deda4-8d62-4c10-be4f-e502362cb18e" version="1.0" stream1:lang="en"/>
2018-11-14 15:12:10:915 Howdoo[847:7803] RECV: <stream:features xmlns:stream="http://etherx.jabber.org/streams"><sm xmlns="urn:xmpp:sm:3"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>ANONYMOUS</mechanism><mechanism>PLAIN_FAST</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression></stream:features>
2018-11-14 15:12:10:918 Howdoo[847:303] SEND: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">ADY3MzE3OTUwLTc0NDQ3AGQ3OGQ4NjBkZmY4ODc1YzU5OGU4YWIwMGYwMjAyYWIy</auth>
2018-11-14 15:12:11:164 Howdoo[847:7803] RECV: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl"/>
2018-11-14 15:12:11:166 Howdoo[847:7803] SEND: <iq type="set" id="6DF51EB6-1905-4453-87BF-210B8A80E6EA"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>D6F3DB59-A0DB-40D9-AF69-16E8E2961361</resource></bind></iq>
2018-11-14 15:12:11.167047+0530 Howdoo[847:215019] [ChatService]: Connected
nil
2018-11-14 15:12:11.168 rtc::[RTCClient] Signaling channel connected
2018-11-14 15:12:11:168 Howdoo[847:7803] SEND: <presence/>
2018-11-14 15:12:11.169089+0530 Howdoo[847:215002] [ChatService]: SNT: <presence/>
2018-11-14 15:12:11:168 Howdoo[847:7803] SEND: <enable xmlns="urn:xmpp:sm:3"/>
2018-11-14 15:12:11:169 Howdoo[847:7803] SEND: <iq type="get" id="BAF3FFAC-2703-438E-851F-B2FA39A96D28"><query xmlns="jabber:iq:roster"/></iq>
2018-11-14 15:12:11.170330+0530 Howdoo[847:215019] [ChatService]: SNT: <iq type="get" id="BAF3FFAC-2703-438E-851F-B2FA39A96D28">
  <query xmlns="jabber:iq:roster"/>
</iq>
2018-11-14 15:12:11:170 Howdoo[847:27a03] SEND: <iq xmlns="jabber:client" type="set" id="A41E59C1-DB6C-4A38-A10F-24E8E45359FE"><enable xmlns="urn:xmpp:carbons:2"/></iq>
2018-11-14 15:12:11.171466+0530 Howdoo[847:215002] [ChatService]: SNT: <iq xmlns="jabber:client" type="set" id="A41E59C1-DB6C-4A38-A10F-24E8E45359FE">
  <enable xmlns="urn:xmpp:carbons:2"/>
</iq>
2018-11-14 15:12:11:406 Howdoo[847:27a03] RECV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="6DF51EB6-1905-4453-87BF-210B8A80E6EA"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361</jid></bind></iq>
2018-11-14 15:12:11.407454+0530 Howdoo[847:215002] [ChatService]: RCV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="6DF51EB6-1905-4453-87BF-210B8A80E6EA">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind">
    <jid>67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361</jid>
  </bind>
</iq>
2018-11-14 15:12:11:644 Howdoo[847:27a03] RECV: <enabled xmlns="urn:xmpp:sm:3"/>
2018-11-14 15:12:11.646690+0530 Howdoo[847:215098] [ChatService]: SMT: <enabled xmlns="urn:xmpp:sm:3"></enabled>
2018-11-14 15:12:11:883 Howdoo[847:18903] RECV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="A41E59C1-DB6C-4A38-A10F-24E8E45359FE"/>
2018-11-14 15:12:11.884619+0530 Howdoo[847:215099] [ChatService]: RCV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="A41E59C1-DB6C-4A38-A10F-24E8E45359FE"/>
2018-11-14 15:12:11:885 Howdoo[847:18903] RECV: <r xmlns="urn:xmpp:sm:3"/>
2018-11-14 15:12:11:885 Howdoo[847:18903] RECV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="BAF3FFAC-2703-438E-851F-B2FA39A96D28"><query xmlns="jabber:iq:roster"/></iq>
2018-11-14 15:12:11.887328+0530 Howdoo[847:215019] [ChatService]: RCV: <iq xmlns="jabber:client" type="result" to="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361" id="BAF3FFAC-2703-438E-851F-B2FA39A96D28">
  <query xmlns="jabber:iq:roster"/>
</iq>
2018-11-14 15:12:11:887 Howdoo[847:18903] RECV: <r xmlns="urn:xmpp:sm:3"/>
2018-11-14 15:12:11:888 Howdoo[847:18903] RECV: <presence xmlns="jabber:client" to="67317950-74447@chat.quickblox.com" from="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361"/>
2018-11-14 15:12:11:888 Howdoo[847:18903] RECV: <r xmlns="urn:xmpp:sm:3"/>
2018-11-14 15:12:11:889 Howdoo[847:18903] SEND: <a xmlns="urn:xmpp:sm:3" h="1"/>
2018-11-14 15:12:11:889 Howdoo[847:7803] SEND: <a xmlns="urn:xmpp:sm:3" h="2"/>
2018-11-14 15:12:11.891707+0530 Howdoo[847:215019] [ChatService]: RCV: <presence xmlns="jabber:client" to="67317950-74447@chat.quickblox.com" from="67317950-74447@chat.quickblox.com/D6F3DB59-A0DB-40D9-AF69-16E8E2961361"/>
2018-11-14 15:12:11:891 Howdoo[847:7803] SEND: <a xmlns="urn:xmpp:sm:3" h="3"/>
2018-11-14 15:12:36:995 Howdoo[847:1b03] RECV: <message xmlns="jabber:client" to="67317950-74447@chat.quickblox.com" id="5bebee0c37b1fa98010041a8" type="headline" from="67317649-74447@chat.quickblox.com/41620F64-8146-4E1F-8E99-4D4456BE29A1"><extraParams xmlns="jabber:client"><callType>1</callType><callerID>67317649</callerID><moduleIdentifier>WebRTCVideoChat</moduleIdentifier><platform>ios</platform><sdp>v=0
o=- 3229132554342780453 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:t3lo
a=ice-pwd:UikgjSruwZktfrPOI6JU7uS7
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:B9:91:E1:C0:26:EA:A2:6A:D8:FB:87:A1:C4:BC:5C:B0:3A:EA:2C:CF:4F:3D:DD:71:13:4D:B2:7A:B8:35:79
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:447471351 cname:UYzL/GS48LGEhZio
a=ssrc:447471351 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] audioTrack
a=ssrc:447471351 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:447471351 label:audioTrack
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:t3lo
a=ice-pwd:UikgjSruwZktfrPOI6JU7uS7
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:B9:91:E1:C0:26:EA:A2:6A:D8:FB:87:A1:C4:BC:5C:B0:3A:EA:2C:CF:4F:3D:DD:71:13:4D:B2:7A:B8:35:79
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 295735171 3449569504
a=ssrc:295735171 cname:UYzL/GS48LGEhZio
a=ssrc:295735171 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] videoTrack
a=ssrc:295735171 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:295735171 label:videoTrack
a=ssrc:3449569504 cname:UYzL/GS48LGEhZio
a=ssrc:3449569504 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] videoTrack
a=ssrc:3449569504 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:3449569504 label:videoTrack
</sdp><sdkVersion>2.7</sdkVersion><sessionID>48EE7490-F823-47FA-9215-906A6F889FA4</sessionID><signalType>call</signalType><userInfo/><opponentsIDs><opponentID>67317950</opponentID></opponentsIDs></extraParams></message>
2018-11-14 15:12:36.997557+0530 Howdoo[847:215005] [ChatService]: RCV: <message xmlns="jabber:client" to="67317950-74447@chat.quickblox.com" id="5bebee0c37b1fa98010041a8" type="headline" from="67317649-74447@chat.quickblox.com/41620F64-8146-4E1F-8E99-4D4456BE29A1">
  <extraParams xmlns="jabber:client">
    <callType>1</callType>
    <callerID>67317649</callerID>
    <moduleIdentifier>WebRTCVideoChat</moduleIdentifier>
    <platform>ios</platform>
    <sdp>v=0
o=- 3229132554342780453 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:t3lo
a=ice-pwd:UikgjSruwZktfrPOI6JU7uS7
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:B9:91:E1:C0:26:EA:A2:6A:D8:FB:87:A1:C4:BC:5C:B0:3A:EA:2C:CF:4F:3D:DD:71:13:4D:B2:7A:B8:35:79
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:447471351 cname:UYzL/GS48LGEhZio
a=ssrc:447471351 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] audioTrack
a=ssrc:447471351 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:447471351 label:audioTrack
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:t3lo
a=ice-pwd:UikgjSruwZktfrPOI6JU7uS7
a=ice-options:trickle renomination
a=fingerprint:sha-256 FC:B9:91:E1:C0:26:EA:A2:6A:D8:FB:87:A1:C4:BC:5C:B0:3A:EA:2C:CF:4F:3D:DD:71:13:4D:B2:7A:B8:35:79
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 urn:3gpp:video-orientation
a=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 VP9/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=rtpmap:123 rtx/90000
a=fmtp:123 apt=127
a=rtpmap:125 red/90000
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=125
a=rtpmap:124 ulpfec/90000
a=ssrc-group:FID 295735171 3449569504
a=ssrc:295735171 cname:UYzL/GS48LGEhZio
a=ssrc:295735171 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] videoTrack
a=ssrc:295735171 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:295735171 label:videoTrack
a=ssrc:3449569504 cname:UYzL/GS48LGEhZio
a=ssrc:3449569504 msid:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649] videoTrack
a=ssrc:3449569504 mslabel:com.quickblox.mediastream.device-iphone10,3_ios-12.0_userid-67317649]
a=ssrc:3449569504 label:videoTrack
</sdp>
    <sdkVersion>2.7</sdkVersion>
    <sessionID>48EE7490-F823-47FA-9215-906A6F889FA4</sessionID>
    <signalType>call</signalType>
    <userInfo/>
    <opponentsIDs>
      <opponentID>67317950</opponentID>
    </opponentsIDs>
  </extraParams>
</message>
2018-11-14 15:12:37.002 rtc::[Signaling Processor] - Did receive signal: call from: 67317649
2018-11-14 15:12:37.022 rtc::[RTCClient] Initializing SSL...
2018-11-14 15:12:37.026 rtc::Create audio track: RTCMediaStreamTrack:
audio
audioTrack
enabled
Live
2018-11-14 15:12:37.026 rtc::[CAPT] Init.
2018-11-14 15:12:37.027 rtc::Create video track: RTCMediaStreamTrack:
video
videoTrack
enabled
Live
2018-11-14 15:12:37.027 rtc::initialize - QBRTCRecorder
2018-11-14 15:12:37.032 rtc::[SESS]<48EE7490-F823-47FA-9215-906A6F889FA4, I:67317649, O:[67317950], T:V> Init.
2018-11-14 15:12:37.032 rtc::[TASK]<ID:2, l:session answer time out> Start.
2018-11-14 15:12:37.033 rtc::[RTCClient] <QBRTCClient: 0x283209dc0> created new [SESS]<48EE7490-F823-47FA-9215-906A6F889FA4, I:67317649, O:[67317950], T:V>
[SESS]<48EE7490-F823-47FA-9215-906A6F889FA4, I:67317649, O:[67317950], T:V>
QBRTCSessionState
2018-11-14 15:12:37.035623+0530 Howdoo[847:214822] -[__NSCFConstantString count]: unrecognized selector sent to

**Steps to reproduce the behavior**

Call this method for video call
let userInfo:[String: String] = ["dialogId": UUID().uuidString]
sesion.startCall(userInfo)

**Any others comments**

**Comment by pwsharma** [comment]
@soulfly @dgem @Nitrino @HoldFast88 hello, guys! please!

**Comment by pwsharma** [comment]
@QB-vladyslav-vyshniak , Do you have any workaround for this issue.
We also have QuickBlox paid enterprise account

**Comment by QB-vladyslav-vyshniak** [comment]
@pwsharma 
Hello.
Thank you for contacting QuickBlox support.
Could you please create a ticket in our support portal and we will consider it as soon as possible.

If you have an additional question, please, let us know.

**Comment by QB-vladyslav-vyshniak** [comment]
@pwsharma 
This issue has been fixed in the last version of IOS SDK - v2.17.1
Please, update to the latest version and check that all works as expected.

If you have any additional questions, please let me know.

**Comment by pwsharma** [comment]
Ok, thanks for the update.
I will check and update you about the issue

**Comment by pwsharma** [comment]
@QB-vladyslav-vyshniak I have updated QuickBlox Web-RTC version to 2.7.2 and still getting the crash. Even worst I am no longer able to test on the simulator because of **missing required architecture x86_64**

[__NSCFConstantString count]: unrecognized selector sent to instance 0x106063120
2019-01-07 14:58:02.878430+0530 Howdoo[265:7591] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString count]: unrecognized selector sent to instance 0x106063120'
*** First throw call stack:
(0x1c2f03ea0 0x1c20d5a40 0x1c2e1cd04 0x1c2f097b8 0x1c2f0b45c 0x10ba98c88 0x10ba8b5d8 0x1006de0d8 0x1c2f0b600 0x1c2de9530 0x1c2dea114 0x105fd7f2c 0x10bf17824 0x10bf18dc8 0x10bf26a78 0x1c2e93dd0 0x1c2e8ec98 0x1c2e8e1cc 0x1c5105584 0x1eff89054 0x100b4d5d8 0x1c294ebb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**When trying to run in the simulator**
Showing All Messages
 ignoring file /Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC, missing required architecture x86_64 in file /Pods/Quickblox-WebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC (2 slices)

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @pwsharma 
Thank you for the report.
Could you please download and testing the latest stable IOS WebRTC version 2.7.3 by these links:
=>>https://cocoapods.org/pods/Quickblox-WebRTC
=>>https://quickbloxwebrtc-sdk.s3.amazonaws.com/ios/QuickbloxWebRTC.framework-2.7.3.zip
It also contains support of architecture x86_64.

**Comment by pwsharma** [comment]
@QB-vladyslav-vyshniak
It's still not fixed please find my crash login Xcode console


2019-01-15 18:57:06.049 rtc::[Signaling Processor] - Did receive signal: call from: 11445
2019-01-15 18:57:06.074 rtc::[RTCClient] Initializing SSL...
2019-01-15 18:57:06.079 rtc::Create audio track: RTCMediaStreamTrack:
audio
audioTrack
enabled
Live
2019-01-15 18:57:06.080 rtc::[CAPT] Init.
2019-01-15 18:57:06.082 rtc::Create video track: RTCMediaStreamTrack:
video
videoTrack
enabled
Live
2019-01-15 18:57:06.083 rtc::initialize - QBRTCRecorder
2019-01-15 18:57:06.097 rtc::[SESS]<C274CFE2-5474-4C7A-A823-81B687317A2B, I:11445, O:[6536], T:V> Init.
2019-01-15 18:57:06.100 rtc::[TASK]<ID:2, l:session answer time out> Start.
2019-01-15 18:57:06.101 rtc::[RTCClient] <QBRTCClient: 0x17027d480> created new [SESS]<C274CFE2-5474-4C7A-A823-81B687317A2B, I:11445, O:[6536], T:V>
[SESS]<C274CFE2-5474-4C7A-A823-81B687317A2B, I:11445, O:[6536], T:V>
QBRTCSessionState
2019-01-15 18:57:06.104619+0530 <My-Project-Name>[267:14200] -[__NSCFConstantString count]: unrecognized selector sent to instance 0x105bff120
2019-01-15 18:57:06.105951+0530 <My-Project-Name>[267:14200] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString count]: unrecognized selector sent to instance 0x105bff120'
*** First throw call stack:
(0x18e0cafe0 0x18cb2c538 0x18e0d1ef4 0x18e0cef54 0x18dfcad4c 0x10b2ecc88 0x10b2df5d8 0x100199410 0x18e0d0e80 0x18dfc62c4 0x18dfcae9c 0x105b73f2c 0x10b769a50 0x10b769a10 0x10b76eb78 0x18e0790c8 0x18e076ce4 0x18dfa6da4 0x18fa11074 0x194261c9c 0x1006085b0 0x18cfb559c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by QB-vladyslav-vyshniak** [comment]
Dear @pwsharma 

Thank you for the report.
Our developers are investigating the provided logs and issue.

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to inactivity.
If the reported issue is still actual for you - please reopen the ticket.

**Comment by meAbhishekTripathi** [comment]
Getting crash on receiver side when created session for Video call on sender side. Delegate of **didReceiveNewSession not called before crashing. It means It somewhere crashing on getting the session.**

Here is the crash log :

2020-07-28 09:38:22.896 rtc::Create audio track: RTCMediaStreamTrack:
audio
audioTrack
enabled
Live
2020-07-28 09:38:22.897 rtc::[CAPT] Init.
2020-07-28 09:38:22.897 rtc::Create video track: RTCMediaStreamTrack:
video
videoTrack
enabled
Live
2020-07-28 09:38:22.899 rtc::initialize - QBRTCRecorder
2020-07-28 09:38:22.964 rtc::[SESS]<EAE09BD2-1FBD-44B0-AC56-4E246A70E556, I:117933348, O:[117932948], T:V> Init.
2020-07-28 09:38:22.967 rtc::[TASK]<ID:5, l:session answer time out> Start.
2020-07-28 09:38:22.967 rtc::[RTCClient] <QBRTCClient: 0x280b67300> created new [SESS]<EAE09BD2-1FBD-44B0-AC56-4E246A70E556, I:117933348, O:[117932948], T:V>
2020-07-28 09:38:22.968801-0400 HQDemand[6281:683068] -[__NSCFConstantString count]: unrecognized selector sent to instance 0x102fc7d50
2020-07-28 09:38:44.303310-0400 HQDemand[6281:683068] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString count]: unrecognized selector sent to instance 0x102fc7d50'
*** First throw call stack:
(0x1c22b3180 0x1c148b9f8 0x1c21cf9bc 0x1c22b89c8 0x1c22ba65c 0x1efff085c 0x1effe5e6c 0x101219ed8 0x1c22ba800 0x1c219c3c0 0x1c219cff4 0x102f4a5e4 0x10764f6f4 0x107650c78 0x10765e6fc 0x1c2244b20 0x1c223fa58 0x1c223efb4 0x1c444079c 0x1eeaa0c38 0x101090bac 0x1c1d028e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by meAbhishekTripathi** [comment]
When you create session from the caller side, make sure you pass nil or use NSString not String for the userInfo.

session?.startCall(nil)
