### ISSUE TITLE
App Crashing in iOS13 for Incoming Audio + Video call

### ISSUE THREAD

**Issue by kushal211** [QuickBlox/quickblox-ios-sdk#1187]
**New Issue Checklist**

 - [x] I have read the [Documentation](https://quickblox.com/developers/IOS)
 - [x] I have searched for a similar issue in the [project](https://github.com/QuickBlox/quickblox-ios-sdk/issues) and found none

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | e.g. 13.1.2                                    |                                          
Quickblox iOS SDK version      | e.g. 2.17.4                                  |
QuickbloxWebRTC SDK version    | e.g. 2.7.4                                 |                               
Xcode Version                  | e.g. Xcode 11.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample? - YES   |

**Did this work before?**
in iOS 12 it was working but for iOS 13 the sample project (sample-videochat-webrtc-swift & sample-videochat-webrtc) is crashing when the app is in the background. 

**Expected behavior**
The app should not crash and receive an incoming call

**Actual behavior**
The app is crashing when it receives a call in the background or not running.

**Logs**

*Please use the following template for logs:*

To enable full logs use the following code:
```objc
[QBSettings setLogLevel:QBLogLevelDebug];
[QBSettings enableXMPPLogging];
```

<details>
<summary>Title for logs </summary>

```logos

// Your logs here

```

</details>

**Steps to reproduce the behavior**
You can easily reproduce this issue in your sample project provided in both **sample-videochat-webrtc-swift & sample-videochat-webrtc**.

**Any others comments**
I checked with iPhone X & iPhone 7 running iOS 13.1.2 & 13.1 with Xcode version 11.1 in your sample project.

There is no issue when app is in the foreground and you make a call request. but as soon as you the app goes to background and you try to make a call, the app is crashing straight away.

**Comment by Rushang007** [comment]
@kushal211 
I had the same issue but when I update my pod file then it's working a charm. 
please update your pod file (Full Update).

**Comment by kushal211** [comment]
Hi @Rushang007 ,  Did you put your application in the background and try calling? I did test this in sample project and every time the sample project app is terminated with the console error - 
```
Assertion failure in -[PKPushRegistry _terminateAppIfThereAreUnhandledVoIPPushes], /BuildRoot/Library/Caches/com.apple.xbs/Sources/PushKit/PushKit-36/PKPushRegistry.m:343
Message from debugger: Terminated due to signal 9
```

I did try updating cocoapods but a result is the same.
Pod version: **1.8.4**
QuickbloxWebRTC SDK: **2.7.4** 
Quickblox SDK: **2.17.4**

**Comment by kushal211** [comment]
Hi, 

Any update on the background VoIP calling issue in iOS 13? Can you guys please help? I still not facing the issue with the sample project provided.

Application terminated straight away from the background when it receives a call / VoIP push.

Any sort of help is deeply appreciated.

**Comment by Rushang007** [comment]
Hey,

have you faced this issue # 1181?

https://github.com/QuickBlox/quickblox-ios-sdk/issues/1181

**Comment by kushal211** [comment]
Hey, I am not allowing app users to log in to multiple devices as of now. I am aware of this problem and did not look into detail as of now. I am yet stuck with this termination issue.

But I think the SDK will have some delegate methods which provide a signal that the call has been answered from another device.

**Comment by Rushang007** [comment]
@kushal211  Thanks for replay 

but I have not found any delegate method and also not working Quickblox demo app (latest).

**Comment by gurpreet029** [comment]
Hey Guys
Not sure if you have fixed this issue or not,
But for me
I have fixed by modifying some of the code
like whenever you receive a VoIP push, you have to trigger the call kit screen, because as of ios13 this is a necessary thing, and after this whenever the users accepts it will call didRecieveSession delegate and you have to just push to ur controller by accepting the call.

**Comment by Rushang007** [comment]
@gurpreet029 
have you faced this issue # 1181?
#1181

**Comment by QB-vladyslav-vyshniak** [comment]
@kushal211 @gurpreet029 @Rushang007 
Is the reported issue still relevant for you?

**Comment by QB-vladyslav-vyshniak** [comment]
The status of the ticket changed to "Closed" due to the absence of a reply.

**Comment by raheeshishan** [comment]
Hi,

How to solve @kushal211 reported issue

**Comment by Rushang007** [comment]
@QB-vladyslav-vyshniak  Yes issue is still there
