### ISSUE TITLE
App crashing issue in ChatViewController in iOS 18 devices

### ISSUE THREAD

**Issue by pratikpatan** [QuickBlox/quickblox-ios-sdk#1375]
Hi team,

I am facing an app crashing issue with the chat classes. I have updated SDKs and classes still facing crash issue. Same crash issue i am also able facing in your `sample-chat-swift` demo project as well.

**Environment details**

Info                           | Value                                       |
-------------------------------|---------------------------------------------|
iOS Version                    | 18.1                                    |                                          
Quickblox iOS SDK version      | 2.20.0                                  |
QuickbloxWebRTC SDK version    | 3.1.0                                  |                               
Xcode Version                  | Xcode 16.1                              |
Repro with our demo sample     | e.g. does it happen with our demo sample?  Yes |

**Did this work before?**
Yes, its working upto iOS 17.5 version.

**Expected behavior**
It should show all the private/group chat in listing.

**Actual behavior**
As soon as i select any user name and go to ChatViewController screen, app is crashing due to below logs. Tried to debug pointer, but couldn't able to do it.

**Logs**
<details>
<summary>Assertion failure in -[sample_chat_swift.ChatCollectionView _updateVisibleCellsNow:], UICollectionView.m:5673 </summary>

```logos

[QBCore]: QBToken expiration date: 2024-12-07 08:52:52 UTC
*** Assertion failure in -[sample_chat_swift.ChatCollectionView _updateVisibleCellsNow:], UICollectionView.m:5673
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Expected dequeued view to be returned to the collection view in preparation for display. When the collection view's data source is asked to provide a view for a given index path, ensure that a single view is dequeued and returned to the collection view. Avoid dequeuing views without a request from the collection view. For retrieving an existing view in the collection view, use -[UICollectionView cellForItemAtIndexPath:] or -[UICollectionView supplementaryViewForElementKind:atIndexPath:]. Dequeued view: <sample_chat_swift.ChatIncomingCell: 0x110984a80; baseClass = UICollectionViewCell; frame = (0 168; 390 44); transform = [1, 0, 0, -1, 0, 0]; opaque = NO; gestureRecognizers = <NSArray: 0x300be10f0>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x3008c8dc0>>; Collection view: <sample_chat_swift.ChatCollectionView: 0x1055e8e00; baseClass = UICollectionView; frame = (0 0; 390 675); transform = [1, 0, 0, -1, 0, 0]; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x300742d90>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x3008fa280>; contentOffset: {0, -28}; contentSize: {390, 222}; adjustedContentInset: {28, 0, 0, 0}; layout: <sample_chat_swift.ChatCollectionViewFlowLayout: 0x1108ed900>; dataSource: <sample_chat_swift.ChatViewController: 0x101eb8500>>'
*** First throw call stack:
(0x19a9687cc 0x197c3b2e4 0x199d388d8 0x19dac4d5c 0x19e2044c4 0x19d279254 0x19d3d17c4 0x19d0d9688 0x19c40fc28 0x19c40f7b4 0x19c466914 0x19c3e57c4 0x19c428a0c 0x19d16f568 0x19d16cb64 0x19d16c9d8 0x19d16c628 0x19d16d59c 0x19a93c328 0x19a93c2bc 0x19a939dc0 0x19a938fbc 0x19a938830 0x1e69181c4 0x19d49eeb0 0x19d54d5b4 0x100268018 0x1c0326ec8)
libc++abi: terminating due to uncaught exception of type NSException

```

</details>

**Steps to reproduce the behavior**
Use iPhone with iOS 18 and select any opponent name in user listing page. If there are some chat messages already exists in the chat, app will crash. But there is no any message, please send atleast 1 message, app will crash after that.

**Comment by IlliaChemolosov** [comment]
Hello @pratikpatan,

Thank you for highlighting this issue! I am from the iOS QuickBlox Team, and I’m happy to let you know that we’ve released a fix. You can find the details here: [Release Notes for 4.12.0-chat-swift-sample](https://github.com/QuickBlox/quickblox-ios-sdk/releases/tag/4.12.0-chat-swift-sample).

Additionally, we recommend exploring our new Sample UIKit for Chatting, which you can find here: [Sample UI Kit](https://github.com/QuickBlox/quickblox-ios-sdk/tree/master/sample-ui-kit).

Feel free to join our Discord community for more updates and support: [Join Discord](https://discord.gg/aFpRptyz).

Thanks again, and we appreciate your collaboration!

**Comment by pratikpatan** [comment]
Thanks for fixing this issue.

**Comment by VijaykumarPalakurthi** [comment]
@IlliaChemolosov, I am still facing this issue on latest sdk

iOS Version | 18.3
Quickblox iOS SDK version | 2.21.0
QuickbloxWebRTC SDK version | 3.1.0
Xcode Version | Xcode 16.1

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Expected dequeued view to be returned to the collection view in preparation for display. When the collection view's data source is asked to provide a view for a given index path, ensure that a single view is dequeued and returned to the collection view. Avoid dequeuing views without a request from the collection view. For retrieving an existing view in the collection view, use -[UICollectionView cellForItemAtIndexPath:] or -[UICollectionView supplementaryViewForElementKind:atIndexPath:]. Dequeued view: <StarChase_AppTrac.ChatIncomingCell: 0x157085c00; baseClass = UICollectionViewCell; frame = (0 10; 414 65); transform = [1, 0, 0, -1, 0, 0]; opaque = NO; gestureRecognizers = <NSArray: 0x30060e030>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x30049a5a0>>; Collection view: <StarChase_AppTrac.ChatCollectionView: 0x156f3ce00; baseClass = UICollectionView; frame = (0 0; 414 726); transform = [1, 0, 0, -1, 0, 0]; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x300ae7ed0>; backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x30048a520>; contentOffset: {0, -28}; contentSize: {414, 147}; adjustedContentInset: {28, 0, 0, 0}; layout: <StarChase_AppTrac.ChatCollectionViewFlowLayout: 0x157090280>; dataSource: <StarChase_AppTrac.ChatViewController: 0x156e78000>>'
*** First throw call stack:
(0x18491a5fc 0x181e95244 0x183d1eec0 0x187aaed24 0x1872b43d8 0x1872b10d8 0x18744abc8 0x187143814 0x186455498 0x186455024 0x1864aa0c4 0x186420d8c 0x186420798 0x1871ab3d0 0x1871a889c 0x1871a8710 0x1871ab040 0x1871a8c5c 0x184960f4c 0x184960ee0 0x184963b40 0x184962d3c 0x1849b5284 0x1d1bf14c0 0x1874fa674 0x187120e88 0x10617f468 0x1aabf5de8)
libc++abi: terminating due to uncaught exception of type NSException
