### ISSUE TITLE
V 2.6.5 breaking changes

### ISSUE THREAD

**Issue by ritesh-nitw** [QuickBlox/quickblox-ios-sdk#282]
**roomJID**  property readonly changes breaking existing app.

This line: dialog.roomJID = self.roomJID; is throwing expection.

[QBChatDialog setRoomJID:]: unrecognized selector sent to instance 0x128c478c0
2016-02-07 02:34:54.758 ui-ios[5788:2115216] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QBChatDialog setRoomJID:]: unrecognized selector sent to instance 0x128c478c0'
*** First throw call stack:

**Comment by Raikerian** [comment]
Hi,

Yes, we have made this property is readonly. There is no need to set it now, our SDK will manage this field itself. Just remove all setters for roomJID from your app and you are good to go.

**Comment by Raikerian** [comment]
If you are getting this issue in our QMServices, then just update them to the latest version 0.3.6, we have fixed it there.

**Comment by nami13** [comment]
I've updated QMServices to 0.4.0 just now.
But this error still happens...
Please help me to find the solution.
Thanks
