### ISSUE TITLE
App crashes when launched on xCode 7 simulator with Quickblox iOS SDK 2.9.0

### ISSUE THREAD

**Issue by icarasiaofficial** [QuickBlox/quickblox-ios-sdk#652]
**Environment details**
*iOS 8, Quickblox iOS SDK 2.9.0,*

**Did this work before?**
Yes, App was working fine on Quickblox iOS SDK 2.8.0.1

**Expected behavior**
Should work on Xcode 7 simulator, right now app starts only on device

**Actual behavior**
App crashes when launched on xcode 7 simulator

**Logs**

[Crash logs](https://gist.github.com/icarasiaofficial/aa193e6dc21fe256874fdd8d874c6cb8)

**Steps to reproduce the behavior**
Run the project using xcode  7

**Comment by adil-appifytech** [comment]
Same issue. Now rolling back to 2.8.0.1

**Comment by Raikerian** [comment]
Please re download it whether you are using cocoapods or this repository, should be fixed now. Seems like if binary was built in xcode 8 it is simply not working with xcode 7 simulators.

**Comment by icarasiaofficial** [comment]
It is still not working at our end. Can somebody confirm if its working at their end. Thanks

**Comment by ErAshu** [comment]
Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 255. The tool may have crashed. Please file a bug report at http://bugreport.apple.com with the above output and attach any crash logs for ibtool, ibtoold, Xcode, and Interface Builder Cocoa Touch Tool created around the time of this failure. These logs can be found in ~/Library/Logs/DiagnosticReports or /Library/Logs/DiagnosticReports.
